CREATE TABLE if not exists routes (
    id integer primary key generated by default as identity,
    route_name text not null,
    dc_area text not null,
    distance integer not null,
    difficulty text not null,
    route_type text not null,
    route_description text not null
);