CREATE TABLE if not exists routes (
    id integer primary key generated by default as identity,
    route_name varchar not null,
    dc_area integer not null,
    distance integer not null,
    difficulty integer not null,
    route_type integer not null,
    route_description varchar not null
);

